---
from: markdown+emoji
format:
  revealjs:
    logo: images/logo-affiliation.png
    footer: "{{< fa brands github >}} &nbsp;[`biodiversitydata/data-access`](https://github.com/biodiversitydata/data-access) &nbsp; &bull; &nbsp; {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} &nbsp;[`cc-by-4.0`](https://creativecommons.org/licenses/by/4.0/deed.en)"
    smaller: true
    auto-stretch: false
    chalkboard: true
    toc-depth: 1
    theme: [default, "styles/main.scss"]
knitr:
  opts_chunk: 
    comment: "##" 
engine: knitr
---

<!-- Insert section 'Title slide' -->

```{r}
#| child: "sections/title-slide.qmd"
```


<!-- Insert section 'Table of contents' -->

```{r}
#| child: "sections/table-of-contents.qmd"
```


<!-- Insert section 'Web portals' -->

```{r}
#| child: "sections/web-portals.qmd"
```


<!-- Insert section 'Scripting' -->

```{r}
#| child: "sections/scripting.qmd"
```


<!-- Insert section 'API' -->

```{r}
#| child: "sections/api.qmd"
```


<!-- Insert section 'Exercise' -->

```{r}
#| child: "sections/exercise.qmd"
```


<!-- Insert section 'Web scraping' -->

```{r}
#| child: "sections/web-scraping.qmd"
```

